### ISSUE TITLE
Error in themes/custom/wxt_bootstrap/templates/system/page.html.twig

### ISSUE THREAD

**Issue by ryanhyma** [drupalwxt/helm-drupal#10]
After deploying the Drupal container, the following error is displayed:
The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">Twig\Error\SyntaxError</em>: The block &#039;header&#039; has already been defined line 120. in <em class="placeholder">Twig\TokenParser\BlockTokenParser-&gt;parse()</em> (line <em class="placeholder">138</em> of <em class="placeholder">themes/custom/wxt_bootstrap/templates/system/page.html.twig</em>).

**Comment by sylus** [comment]
How have you deployed this?

This was fixed in a newer release of this helm chart.

Thanks!

**Comment by ryanhyma** [comment]
With the newer version of the helm chart, the site install script doesn't run for me. I'm able to manually install if I disable the script. I'm using the terraform scripts from your statcan repo: https://github.com/StatCan/terraform-kubernetes-aks

Last week, I would see the instller jobs running, now the only job I see is the bucket creation. I make sure to run helm delete drupal then helm delete drupal -purge between requests, the kubectl get all to verify everything has been removed.

**Comment by sylus** [comment]
We added you to our slack channel so can go back and forth a bit faster, and see what is up. Everything honestly should just run with no intervention.

@zachomedia send you a response in email :D

**Comment by sylus** [comment]
Worked with you on this and think is good now :D
