### ISSUE TITLE
Error encountered during module installation

### ISSUE THREAD

**Issue by canasa21** [drupalwxt/helm-drupal#104]
Hello, we are attempting to configure the Helm Chart Drupal WxT for development purposes and ran into trouble when installing modules. Could this be related to a configuration issue from our installation? This error also appeared during an unrelated process and failed for the same script but different line number. Thank you.

Here are the details:
Extend > Install new module
config_devel-8x-1.8.tar.gz

Notice: Undefined index: persistent in Drupal\redis\ClientFactory::getClient() (line 190 of /var/www/html/modules/contrib/redis/src/ClientFactory.php).The website encountered an unexpected error. Please try again later.
RuntimeException: Failed to start the session because headers have already been sent by "/var/www/html/core/includes/errors.inc" at line 285. in Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->start() (line 152 of /var/www/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php).

Alex

**Comment by sylus** [comment]
You have to install your module using composer i am assuming you did this through the UI which can't be done as it has to be part of the container image.

The other issue is a redis issue but is merely a warning that will be fixed in the next release of WxT.
