### ISSUE TITLE
Is osb a working feature?

### ISSUE THREAD

**Issue by ryanhyma** [drupalwxt/helm-drupal#12]
Enabling it, and disabling mysql results in yaml errors.

**Comment by sylus** [comment]
Hey this does work but it is a bit finicky, I'd have to know more about errors.

That being said think it is easier to setup the Managed DB via Terraform / Manual, and then can pass those values to the helm chart.

We just got everything working via NFS with Azure Files so now that we don't need minio will be adding the ability to use Managed DB whether MySql / PostgreSQL next.
