### ISSUE TITLE
Sending Drupal logs to syslog

### ISSUE THREAD

**Issue by bernardmaltais** [drupalwxt/helm-drupal#120]
Good afternoon @sylus ,

I wonder if you have ever tried to configure your drupal site to send logs to syslog vs the mysql DB? We have tried at our end and can't see any logs in the pod when trying to do this.

Any ideas?

Bernard

**Comment by sylus** [comment]
I think maybe take a look at:

https://drupal.org/project/log_stdout

And can add to your composer.json. Then can use fluent bit and relay.

**Comment by bernardmaltais** [comment]
Manu thanks @sylus. This is exactly what we needed!
