### ISSUE TITLE
Drupal 7 redis documentation and chart versions don't align

### ISSUE THREAD

**Issue by nathanpw** [drupalwxt/helm-drupal#127]
Steps to recreate:
- browse to https://github.com/drupalwxt/helm-drupal/tree/master/drupal7
- take note of teh redis version as of this writing "https://charts.bitnami.com/bitnami | redis | 12.10.1"
- Look at the chart.yml https://github.com/drupalwxt/helm-drupal/blob/master/drupal7/Chart.yaml :  name: redis   version: 15.7.4

Expected results the documentation should match the chart?

Problem the Chart anbd documentation specify different versions.

**Comment by sylus** [comment]
Looks like @zachomedia forgot to run helm-docs which i just did and should be good now!

https://github.com/drupalwxt/helm-drupal/commit/f4c56f4322380a5b782329a2874753195a74d030

**Comment by nathanpw** [comment]
Thanks, appreciate you @sylus and @zachomedia !
