### ISSUE TITLE
ValidationError(Deployment.spec.template.spec.volumes[1]): unknown field

### ISSUE THREAD

**Issue by ryanhyma** [drupalwxt/helm-drupal#14]
With the current build, and most recent helm:
helm install drupaltest -f values-nfs-azurefile.yaml --wait --timeout 5m --namespace drupaltest .
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.volumes[1]): unknown field "items" in io.k8s.api.core.v1.Volume

removeing the items element from the drupal.yaml allows the deployment to start, but is probably not a proper fix.

**Comment by zachomedia** [comment]
@ryanhyma Can you try the updated chart? It looks like the items field was incorrect indented and should have been under `secret`

**Comment by ryanhyma** [comment]
Seems to run without issue now.
