### ISSUE TITLE
Install fails when using NFS and defaults

### ISSUE THREAD

**Issue by ryanhyma** [drupalwxt/helm-drupal#15]
helm install drupaltest -f values-nfs-azurefile.yaml --wait --timeout 20m --namespace drupaltest .

The pods come up but the installation fails with the following:
 // You are about to DROP all tables in your 'wxt' database. Do you want to     
 // continue?: yes.                                                             

 [notice] Starting Drupal installation. This takes a while.

In FileSystem.php line 506:
                                                                               
  File 'modules/contrib/video_embed_field/modules/video_embed_media/images/ic  
  ons/video.png' could not be copied because a file by that name already exis  
  ts in the destination directory ('').

**Comment by sylus** [comment]
Oh! There is a fix for this, I totally forgot to commit, for some reason we need to create that as a folder ahead of time and if we do that we get around this issue. I will commit it this weekend! @zachomedia

**Comment by sylus** [comment]
This should be fixed now :D 

https://github.com/drupalwxt/helm-drupal/commit/5454b8dce94b88a12fc49d950409769cf81b7ad6
