### ISSUE TITLE
drupal-site-install - Errors setting file permissions

### ISSUE THREAD

**Issue by ryanhyma** [drupalwxt/helm-drupal#16]
The install does work, but the log does not look, maybe not important:

[warning] chmod(): Operation not permitted FileSystem.php:236
 [success] Installation complete.
real	3m 55.02s
user	1m 24.62s
sys	0m 15.01s

 // Do you want to update wxt.theme key in wxt_library.settings config?: yes.   

 [success] Cache rebuild complete.
 [error]  The file permissions could not be set on public://218x291.png. 

  1/13 [==>-------------------------]   7% [error]  The file permissions could not be set on public://265x352.png. 

  2/13 [====>-----------------------]  15% [error]  The file permissions could not be set on public://355x113.png. 

  3/13 [======>---------------------]  23% [error]  The file permissions could not be set on public://360x203.png. 

  4/13 [========>-------------------]  30% [error]  The file permissions could not be set on public://520x296.png. 

  5/13 [==========>-----------------]  38% [error]  The file permissions could not be set on public://653x194-1.png. 

  6/13 [============>---------------]  46% [error]  The file permissions could not be set on public://653x194-2.png. 

  7/13 [===============>------------]  53% [error]  The file permissions could not be set on public://653x194-3.png. 

  8/13 [=================>----------]  61% [error]  The file permissions could not be set on public://750x222-1.png. 

  9/13 [===================>--------]  69% [error]  The file permissions could not be set on public://750x222-2.png. 

 10/13 [=====================>------]  76% [error]  The file permissions could not be set on public://1170x347-1.png. 

 11/13 [=======================>----]  84% [error]  The file permissions could not be set on public://1170x347-2.png. 

 12/13 [=========================>--]  92% [error]  The file permissions could not be set on public://1170x347-3.png. 

 13/13 [============================] 100% [notice] Processed 13 items (13 created, 0 updated, 0 failed, 0 ignored) - done with 'wxt_file'
 [notice] Processed 0 items (0 created, 0 updated, 0 failed, 0 ignored) - done with 'wxt_file'

 1/2 [==============>-------------]  50%
 2/2 [============================] 100% [notice] Processed 2 items (2 created, 0 updated, 0 failed, 0 ignored) - done with 'wxt_node_page'

  1/13 [==>-------------------------]   7%
  2/13 [====>-----------------------]  15%
  3/13 [======>---------------------]  23%
  4/13 [========>-------------------]  30%
  5/13 [==========>-----------------]  38%
  6/13 [============>---------------]  46%
  7/13 [===============>------------]  53%
  8/13 [=================>----------]  61%
  9/13 [===================>--------]  69%
 10/13 [=====================>------]  76%
 11/13 [=======================>----]  84%
 12/13 [=========================>--]  92%
 13/13 [============================] 100% [notice] Processed 13 items (13 created, 0 updated, 0 failed, 0 ignored) - done with 'wxt_media'

 1/3 [=========>------------------]  33%
 2/3 [==================>---------]  66%
 3/3 [============================] 100% [notice] Processed 3 items (3 created, 0 updated, 0 failed, 0 ignored) - done with 'wxt_media_slideshow'

 1/4 [=======>--------------------]  25%
 2/4 [==============>-------------]  50%
 3/4 [=====================>------]  75%
 4/4 [============================] 100% [notice] Processed 4 items (4 created, 0 updated, 0 failed, 0 ignored) - done with 'gcweb_block'

 1/3 [=========>------------------]  33%
 2/3 [==================>---------]  66%
 3/3 [============================] 100% [notice] Processed 3 items (3 created, 0 updated, 0 failed, 0 ignored) - done with 'gcweb_block_spotlight'

 1/2 [==============>-------------]  50%
 2/2 [============================] 100% [notice] Processed 2 items (2 created, 0 updated, 0 failed, 0 ignored) - done with 'gcweb_node_landing_page'

  3/38 [==>-------------------------]   7%
  6/38 [====>-----------------------]  15%
  9/38 [======>---------------------]  23%
 12/38 [========>-------------------]  31%
 15/38 [===========>----------------]  39%
 18/38 [=============>--------------]  47%
 21/38 [===============>------------]  55%
 24/38 [=================>----------]  63%
 27/38 [===================>--------]  71%
 30/38 [======================>-----]  78%
 33/38 [========================>---]  86%
 36/38 [==========================>-]  94%
 38/38 [============================] 100% [notice] Processed 38 items (38 created, 0 updated, 0 failed, 0 ignored) - done with 'gcweb_menu_link'

**Comment by zachomedia** [comment]
@ryanhyma Yeah, that's expected because of how Azure's file shares implements access control. 

> If you mount the file share by using SMB, you don't have folder-level control over permissions. (https://docs.microsoft.com/en-us/azure/storage/files/storage-files-faq)

Because of this, calls to `chmod` fail but can be ignored in this case.

**Comment by ryanhyma** [comment]
Closing issue.
