### ISSUE TITLE
varnish pod crashloopback

### ISSUE THREAD

**Issue by bernardmaltais** [drupalwxt/helm-drupal#38]
Trying to make use of the recently updated varnish template result in a pod crashloopback with the following error:

![image](https://user-images.githubusercontent.com/25299479/99905405-97502900-2c9e-11eb-92d6-bfdae9a144eb.png)

```
Error:
--
Sun, Nov 22 2020 8:38:21 am | Message from VCC-compiler:
Sun, Nov 22 2020 8:38:21 am | Backend host '"drupal-wxt-varnish-drupal"' could not be resolved to an IP address:
Sun, Nov 22 2020 8:38:21 am | Name or service not known
Sun, Nov 22 2020 8:38:21 am | (Sorry if that error message is gibberish.)
Sun, Nov 22 2020 8:38:21 am | ('/etc/varnish/default.vcl' Line 4 Pos 11)
Sun, Nov 22 2020 8:38:21 am | .host = "drupal-wxt-varnish-drupal";
Sun, Nov 22 2020 8:38:21 am | ----------###########################-
Sun, Nov 22 2020 8:38:21 am |  
Sun, Nov 22 2020 8:38:21 am |  
Sun, Nov 22 2020 8:38:21 am | In backend specification starting at:
Sun, Nov 22 2020 8:38:21 am | ('/etc/varnish/default.vcl' Line 3 Pos 1)
Sun, Nov 22 2020 8:38:21 am | backend default {
Sun, Nov 22 2020 8:38:21 am | #######----------
Sun, Nov 22 2020 8:38:21 am |  
Sun, Nov 22 2020 8:38:21 am | Running VCC-compiler failed, exited with 2
Sun, Nov 22 2020 8:38:21 am | VCL compilation failed
```

**Comment by bernardmaltais** [comment]
I think it has to do with the host name it is trying to find. It is looking for `drupal-wxt-varnish-drupal` but that name does not exist. On the other hand `drupal-wxt-varnish` does exist.

**Comment by bernardmaltais** [comment]
Also, looking at the template code I am not sure varnish would actually get used as I am not finding code that would reconfigure the ingress to use varnish instead of nginx. Is it possible this just deploy varnish without integrating it in the flow between the user and nginx?

**Comment by sylus** [comment]
Ah sorry this was pushed half done, and it was supposed to be updated last week from our working internal.

I have just synced it right now in this P.R. and waiting for @zachomedia to approve it :D 

https://github.com/drupalwxt/helm-drupal/pull/40/files

**Comment by bernardmaltais** [comment]
Well well well... after digging a bit more in the varnish chart I figured there is a very important value that actually need to be passed within the `varnish:` section of the helm-drupal char values.yaml... the `varnishConfigContent` value. After setting it to the appropriate values things appear to deploy properly. The default ingress is still not pointing to varnish so no traffic actually goes through it but it does deploy properly.

I think this value should not have to be provided in the values file and a proper default for helm-drupal should be baked into the chart to make it work out of the box...

Varnish appear to be very much a work in progress?

**Comment by sylus** [comment]
Ah @bernardmaltais  think you just posted after what I just posted :P 

There is a P.R. with all this working just waiting on @zachomedia to approve it

https://github.com/drupalwxt/helm-drupal/pull/40/files

We do also bake all of this into the chart so shouldn't be anything you have to do :D

**Comment by bernardmaltais** [comment]
@sylus Nice. I was wondering about that. This gave me a chance to poke at the bear so to speak to make it growl ;-) I will look forward to the merge for the update. Many thanks!

**Comment by sylus** [comment]
Is now merged :D 

https://github.com/drupalwxt/helm-drupal/pull/40

**Comment by sylus** [comment]
1) kind create cluster --config kind.yaml

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # add a mount from /path/to/my/files on the host to /files on the node
  extraMounts:
  - hostPath: /tmp/drupal/shared/drupal-public
    containerPath: /mnt/drupal/drupal-public
  - hostPath: /tmp/drupal/shared/drupal-private
    containerPath: /mnt/drupal/drupal-private
```

2) helm install drupal -f values-hostpath-kind.yaml --set varnish.enabled=true .

**Comment by bernardmaltais** [comment]
@sylus That was quick! It does indeed deploy perfectly now! Nice work guys! We are debating internally between building our deployment in Azure App Services using containers or leveraging this great piece of work. Obviously I am for reusing your work as this is the reason you make this open and available with great support.

I have a few questions regarding how to best operate the solution once deployed so I will probably reach out eventually to discuss what you would consider best day two operations practices.

**Comment by sylus** [comment]
Awesome to hear and yeah Zachary is going to get back to your email soon we did a whole write up aboutsome of the downsides of Azure Web Apps (and why is disabled at our dept since we have a platform team) and Zachary will give you a detailed reply. We could also share our security controls, and concept of operations that we recieved an ATO for our cloud platform with.

In essence Azure Web Apps is okay but you won't really get to much control or useful scaling. However if you are only doing one app then it might makes sense. For us we use our cloud native platform so logging in our Elastic stack using the operator, credentials in vault, and real time metrics in Prometheus / Grafana. Then having everything under Mutual TLS through the Istio service mesh. The value is only really achieved when you have multiple workloads running under it though due to economy of scale and making it an organizational shift to use that workflow. Another big reason is the community we get to work with and ability to jump to any cloud. Also that we are GCEARB endorsed.

https://github.com/canada-ca-terraform-modules/terraform-kubernetes-aks
https://github.com/canada-ca-terraform-modules/terraform-kubernetes-aks-platform

**Comment by bernardmaltais** [comment]
Awesome! This will be very helpful for us. It is nice to stand on the shoulder of a giant ;-)

**Comment by sylus** [comment]
@bernardmaltais 

If you get a chance try out Kind for local dev https://kind.sigs.k8s.io/

I tested varnish myself and worked and showed all the steps here:

https://github.com/drupalwxt/helm-drupal/issues/38#issuecomment-731815239

**Comment by sylus** [comment]
Closing this out thanks for testing it :D

**Comment by sylus** [comment]
@bernardmaltais 

Remember we do have this here but it doesn't have the pgbouncer and varnish configurations:

https://github.com/drupalwxt/terraform-containers-webapp-azure

Also we have this if you decide to go for Managed Postgresql which our chart supports external dbs:

https://github.com/canada-ca-terraform-modules/terraform-azurerm-postgresql

**Comment by sylus** [comment]
@bernardmaltais just in case you decide to test the redis integration you will need to run chart version 0.6.6 and point to these images until the next release as we just added the redis library https://github.com/drupalwxt/docker-scaffold/commit/1deda6b47e65a94618801e2e807e7821a3a045d6

drupalwxt/site-wxt:4.0.0-rc1-redis
drupalwxt/site-wxt:40.0-rc1-redis-nginx

**Comment by sylus** [comment]
@bernardmaltais sorry chart version 0.6.7+
