### ISSUE TITLE
Azure fileshare on Kubernetes 1.19 bug

### ISSUE THREAD

**Issue by thomascraig** [drupalwxt/helm-drupal#56]
discovered a little bug when deploying to kubernetes 1.19 on AKS with Azure fileshare - in your values.yaml file lines 286 and 293 need to append the secretNamespace or it looks in the default namspace, existing code:

      `secretName: drupal-storage`
      `shareName: drupal-public`
      `readOnly: false`

fix is to include the secretNamespace attr:

     `secretName: drupal-storage`
     `secretNamespace: {active-ns}`
     `shareName: drupal-public`
     `readOnly: false`

**Comment by sylus** [comment]
I added this as an inline comment in https://github.com/drupalwxt/helm-drupal/issues/56

Does that work for you? I don't seem to experience this in Kubernetes 1.17 atm.

**Comment by sylus** [comment]
Thinking we good with P.R. :D please reopen if not

**Comment by thomascraig** [comment]
yes, comment works.  thanks.
