### ISSUE TITLE
Azure files: storageClassName field is set when deploying PV objects

### ISSUE THREAD

**Issue by zachomedia** [drupalwxt/helm-drupal#60]
This results in an unmapped PVC.

**Comment by sylus** [comment]
https://github.com/drupalwxt/helm-drupal/pull/57/files

Based on this P.R. does the default in values.yaml just need to be; "-" ?

**Comment by sylus** [comment]
I documented in values-azurefile.yaml that if you enable azureFile option you also have to set storageClass: "-"
