### ISSUE TITLE
Backup script will capture the DB cache and will create huge backup files as a result

### ISSUE THREAD

**Issue by bernardmaltais** [drupalwxt/helm-drupal#80]
Hello guys,

I am looking at a way to feed an ignore tables list to the backup job to prevent exporting useless tables like cache. At the moment I don't see a way to do this in the chart short of not enabling backup and creating my own cronjob outside the helm chart... but we are using the chart because everything needed is available in there... so it would defeat the purpose.

Is this something you had on the roadmap? How do you handle not backing caches in the DB for your own deployment?

I might propose an idea. How about adding an optional value to the backup section where we could capture extra `drush -y sql-dump` options? That way we could specify which tables to ignore with:

```yaml
# Add option extra options to the drush -y sql-dump command
extra_options: --skip-tables-list=cache,cache_*
```

If you are interested I could submit a PR with the proposed changes to support the feature?

Bernard

**Comment by sylus** [comment]
Looks like we only added this in D7 so should add it to D9 as well :D 

https://github.com/drupalwxt/helm-drupal/commit/4f3ac6e0f553dddc8cc44571a3554d3301949478

**Comment by bernardmaltais** [comment]
I see it in D7, you are right ;-) OK, no need for my PR then. I will let you add this simple fix ;-)

**Comment by sylus** [comment]
This should do it thanks so much :D 

https://github.com/drupalwxt/helm-drupal/commit/259ea8ac3be7c057f849917d1f671e3f9fd49edc
