### ISSUE TITLE
drush query to see if network and database is available for additionalCrons

### ISSUE THREAD

**Issue by kieran-github** [drupalwxt/helm-drupal#91]
Hello,

Would it be possible to implement the following code for "additionalCrons" in order for cron containers to realize network and database connectivity:
```
# Wait for DB and network to be available
until drush sql:query 'SHOW TABLES;'; do echo Waiting for DB; sleep 3; done
echo DB available
```
I believe this is due to latency between the proxy and cron containers initialization?

Thanks.

**Comment by sylus** [comment]
@zachomedia thoughts?

**Comment by zachomedia** [comment]
@sylus This is the correct thing to do, I think I missed including it when I built the additional cron job feature - I asked them to open this issue if the fix resolved the issue they were experiencing.

**Comment by sylus** [comment]
I think now we allow this whole section to be brought in via the values.yaml and overwritten depending on the end users neat :) I think this may close this one out!
