### ISSUE TITLE
Remove requirement for lightning_core to be enabled.

### ISSUE THREAD

**Issue by vitaliss** [drupalwxt/helm-drupal#93]
While attempting to deploy to Prod I'm running into the error where lighting is trying to update. Since minimal version doesn't require lightning_core to be enabled, I'd like to remove the requirement (drush -y update:lightning) that it be enabled. That way it can be manually added to extraInstallScripts for the apps that still make use of Lighting. If that would break too many apps, could a way of disabling update:lighting be devised?

**Comment by sylus** [comment]
Can u just wrap that lightning_core into only being added if boolean true? Then you can set it to false to override this default behavior?

**Comment by vitaliss** [comment]
```
diff --git a/drupal/templates/job/post-upgrade-reconfigure.yaml b/drupal/templates/job/post-upgrade-reconfigure.yaml
index 55c8a46..e9e4e8b 100644
--- a/drupal/templates/job/post-upgrade-reconfigure.yaml
+++ b/drupal/templates/job/post-upgrade-reconfigure.yaml
@@ -85,8 +85,10 @@ spec:
               drush -y updatedb
 
               # Lightning updates
+              {{- if .Values.drupal.lightningUpdate }}
               drush -y cache:rebuild
               drush -y update:lightning
+              {{- end }}
 
               # WxT updates
               drush -y cache:rebuild
```
Thanks Will. Would this work? Then I set it to false in my .tf file?

**Comment by vitaliss** [comment]
I made a PR. https://github.com/drupalwxt/helm-drupal/pull/94

**Comment by sylus** [comment]
Hey @vitaliss almost there,

Can you go to values.yaml and set this parameter to true by default.

Then yes in yours would set to false but we need the default set so no changes happen to existing users.

Also if can bump the chart version in chart.yaml :D 

Thx!

**Comment by vitaliss** [comment]
Done. Thanks @sylus

**Comment by sylus** [comment]
Thanks @vitaliss all merged and passed :D
